### PR TITLE
Change the way to compute wssse when creating glance_tbl for kmeans and bisecting_kmeans 

### LINKED ISSUE #2183: Error in test-broom-kmeans.R with Spark 3.0
When testing with spark 3.0, I got the following error:

```r
test-broom-kmeans.R:48: error: kmeans.glance() works
All columns in a tibble must be 1d or 2d objects:
* Column `wssse` is NULL
```
This is because kmeans model does not return cost anymore, which causes the failure from `glance.ml_model_kmeans` 
https://github.com/rstudio/sparklyr/blob/master/R/tidiers_ml_unsupervised_models.R#L52

### PR DESCRIPTION
**Pull request by lu-wang-dl**
This is to fix #2183 .

- Add `training_cost ` with spark 2.4 or later in the summary
- Update the way to comput `wssse` for `glance_tbl`

### CODE REVIEW

**Comment by javierluraschi** [comment]
Not sure why AppVeyor did not fail, but just fixed this:

```
ft_one_hot_encoder
  Code: function(x, input_cols = NULL, output_cols = NULL,
                 handle_invalid = NULL, drop_last = TRUE, uid =
                 random_string("one_hot_encoder_"), ...)
  Docs: function(x, input_col = NULL, output_col = NULL, drop_last =
                 TRUE, uid = random_string("one_hot_encoder_"), ...)
  Argument names in code not in docs:
    input_cols output_cols handle_invalid
  Argument names in docs not in code:
    input_col output_col
  Mismatches in argument names (first 3):
    Position: 2 Code: input_cols Docs: input_col
    Position: 3 Code: output_cols Docs: output_col
    Position: 4 Code: handle_invalid Docs: drop_last
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
```

with https://github.com/rstudio/sparklyr/commit/9363ece23c1217dd03d88e67d48a400cb685cd93, we will need to rebase to get that fix.

**Comment by javierluraschi** [comment]
Oh, never mind about my test comment, looks like we need to properly configure AppVeyor to trigger in PRs from forks.

File: R/ml_clustering_bisecting_kmeans.R [hunk 1]
```diff
@@ -147,7 +147,16 @@ new_ml_bisecting_kmeans_model <- function(jobj) {
...
 new_ml_bisecting_kmeans_summary <- function(jobj) {
-  new_ml_clustering_summary(
+  sc <- spark_connection(jobj)
+  version <- spark_version(sc)
+
+  bisecting_kmeans_summary <- new_ml_clustering_summary(
     jobj,
     class = "ml_bisecting_kmeans_summary")
+
+  if (version >= "3.0.0") {
```
Comment (javierluraschi) [inline R/ml_clustering_bisecting_kmeans.R]: Since you added `is_spark_3`, we could expand this function to support connections and `jobs` with something like:

```
is_spark_3 <- function(x) {
  UseMethod(""is_spark_3)
}

is_spark_3.spark_connection <- function(x) {
  version <- spark_version(x)
  version >= "3.0.0"
}

is_spark_3.spark_jobj <- function(x) {
  sc <- spark_connection(x)
  is_spark_3(sc)
}
```

File: R/ml_clustering_kmeans.R [hunk 2]
```diff
@@ -148,7 +148,16 @@ new_ml_kmeans_model <- function(jobj) {
...
 new_ml_kmeans_summary <- function(jobj) {
-  new_ml_clustering_summary(
+  sc <- spark_connection(jobj)
+  version <- spark_version(sc)
+
+  kmeans_summary <- new_ml_clustering_summary(
     jobj,
     class = "ml_kmeans_summary")
+
+  if (version >= "2.4.0") {
```
Comment (javierluraschi) [inline R/ml_clustering_kmeans.R]: Similar here, we could have `is_spark_2_4()` and remove `sc` and `version`.

Comment (javierluraschi) [reply R/ml_clustering_kmeans.R]: We could also consider refactoring `is_spark_3()` and `is_spark_2_4()` into `is_spark("3.0")` and `is_spark("2.4")`.

File: R/ml_clustering_bisecting_kmeans.R (hunk 1 above)
Comment (lu-wang-dl) [reply R/ml_clustering_bisecting_kmeans.R]: This is good, not know that.

Comment (javierluraschi) [reply R/ml_clustering_bisecting_kmeans.R]: Here is more about S3 (one of various class systems available in R): http://adv-r.had.co.nz/S3.html
